name: CI/CD for Helm Charts

on:
  pull_request:
    paths:
      - 'charts/**'
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  validate-pr:
    uses: ./.github/workflows/validate-pr.yaml

  lint-and-test:
    needs: validate-pr
    uses: ./.github/workflows/lint-test.yaml

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: lint-and-test
    uses: ./.github/workflows/release.yaml