name: Release Helm Chart

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Determine Version Increment
        id: determine_version
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if echo "$commit_message" | grep -q '\[major\]'; then
            increment=major
          elif echo "$commit_message" | grep -q '\[minor\]'; then
            increment=minor
          else
            increment=patch
          fi
          echo "increment=$increment" >> $GITHUB_ENV

      - name: Bump Chart Version
        id: bump_version
        run: |
          current_version=$(yq e '.version' charts/*/Chart.yaml)
          IFS='.' read -r major minor patch <<< "$current_version"
          case "$increment" in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            patch)
              patch=$((patch + 1))
              ;;
          esac
          new_version="$major.$minor.$patch"
          yq e '.version = env(new_version)' -i charts/*/Chart.yaml
          echo "Bumped version from $current_version to $new_version"

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts

      - name: Publish Changes
        run: |
          git add .
          git commit -m "Update chart repository index and version"
          git push origin main