name: Release Helm Chart

on:
  workflow_call:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"    

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Helm
#         uses: azure/setup-helm@v4

#       - name: Determine Version Increment
#         id: determine_version
#         run: |
#           commit_message=$(git log -1 --pretty=%B)
#           if echo "$commit_message" | grep -q '\[major\]'; then
#             increment=major
#           elif echo "$commit_message" | grep -q '\[minor\]'; then
#             increment=minor
#           else
#             increment=patch
#           fi
#           echo "increment=$increment" >> $GITHUB_ENV

#       - name: Bump Chart Version
#         id: bump_version
#         run: |
#           current_version=$(yq e '.version' charts/*/Chart.yaml)
#           IFS='.' read -r major minor patch <<< "$current_version"
#           case "$increment" in
#             major)
#               major=$((major + 1))
#               minor=0
#               patch=0
#               ;;
#             minor)
#               minor=$((minor + 1))
#               patch=0
#               ;;
#             patch)
#               patch=$((patch + 1))
#               ;;
#           esac
#           new_version="$major.$minor.$patch"
#           yq e '.version = env(new_version)' -i charts/*/Chart.yaml
#           echo "Bumped version from $current_version to $new_version"

#       - name: Run Chart Releaser
#         uses: helm/chart-releaser-action@v1.6.0
#         env:
#           CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           charts_dir: charts

#       - name: Publish Changes
#         run: |
#           git add .
#           git commit -m "Update chart repository index and version"
#           git push origin main