name: Validate Pull Request

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate PR changes
        run: |
          modified_charts=$(git diff --name-only origin/main | grep -c '^charts/')
          if [ "$modified_charts" -ne 1 ]; then
            echo "Only one chart can be modified per PR."
            exit 1